### ISSUE TITLE
'fwd2_solver' seems to have a problem.

### ISSUE THREAD

**Issue by chenglong0791** [rawlings-group/paresto#8]
Error using casadi.Function/call (line 2467)
Error in Function::call for 'fwd2_solver' [MXFunction] at
.../casadi/core/function.cpp:1401:
.../casadi/core/function_internal.hpp:1086: FunctionInternal::index_in:
could not find entry "in_lam_g0". Available names are: [x0, p, lbx, ubx,
lbg, ubg, lam_x0, lam_g0, out_x, out_f, out_g, out_lam_x, out_lam_g,
out_lam_p, fwd_x0, fwd_p, fwd_lbx, fwd_ubx, fwd_lbg, fwd_ubg, fwd_lam_x0,
fwd_lam_g0].

Error in casadi.Function/paren (line 5366)
        res = self.call(arg);

Error in casadi.Function/subsref (line 5351)
        [varargout{1:nargout}]= paren(self, s.subs{:});

Error in paresto/optimize (line 678)
	fsol = self.fsolver('in_x0', sol.x, 'in_lam_x0', sol.lam_x, 'in_lam_g0', sol.lam_g,...

Error in Sfirstorder (line 79)
[est, y, p] = pe.optimize(y_ac, theta0, lb, ub);

**Comment by titusswsquah** [comment]
commit f5e85ee8eab5ddfb3e2575d4f495f6d73283111c resolves this issue

**Comment by jbraw** [comment]
This set of changes isn't quite right. Can you go to green_book/ and start
octave and run the file runall.m.  Most of them now fail with the same
error.

Jim

Running book scripts.

* adsone ... success (0.3452 s)
* adsall ... success (1.165 s)
* batch_data_solution ... FAILURE (0.04062 s)
* bvsm ... FAILURE (0.06784 s)
* bvsm_red ... FAILURE (0.0668 s)
* estdiff ... FAILURE (0.03414 s)
* fitrtd ... FAILURE (0.05461 s)
* hbv_det ... FAILURE (0.0668 s)
* hbv_red ... FAILURE (0.06968 s)
* react2rev ... FAILURE (0.04393 s)
* ABC ... FAILURE (0.04504 s)
* Sfirstorder ... FAILURE (0.03161 s)
*** batch_data_solution ***
    message = casadiMEX: Sparsity::row: Index 0 out of range [0,0)
    identifier = SWIG:RuntimeError
    stack =

      7x1 struct array containing the fields:

        file
        name
        line
        column

    file =
/home/jbraw/src/casadi/casadi-3.6.5-linux64-octave7.3.0/+casadi/GenericMatrixCommon.m
    name = det
    line = 485
    column = 29
    file = /home/jbraw/src/paresto/paresto.m
    name = modeling
    line = 196
    column = 26
    file = /home/jbraw/src/paresto/paresto.m
    name = paresto
    line = 149
    column = 7
    file = /home/jbraw/src/paresto/examples/green_book/batch_data_solution.m
    name = batch_data_solution
    line = 71
    column = 4

**Comment by jbraw** [comment]
Hi Titus.

I also logged into bucky and tried to remove them with the failure given
below.

It looks like a bad few blocks on the disk. When disks start to go they can
fail all at once, or they make a read or write error on a portion of the
disk and damage it.

I think it's only Min's files because only a small portion was damaged, and
that was where her files had been written.

How old is the disk?  I suggest that we  just replace it.  I don't think
it's worth the trouble to unmount it, check it with a disk "bad blocks"
locator, and repartition the disk to avoid that part of the disk, because
the hardware is so old.   And we might find that it happens again in a
month, and it's not worth our time to do it twice.

Anyway, this is why we do backups, so some disk crash does not take out
files that we care about and need immediately.

You can get big disks really cheap these days.

What do you think?

Jim


***@***.***:/mirror/ARCHIVE$ sudo rm -Rf
amyao/Documents/toshiba_Research2014/AIChE\
prep/talks_slides/aichetalk/.hg/store/data/*
[sudo] password for jbraw:
rm: cannot remove 'amyao/Documents/toshiba_Research2014/AIChE
prep/talks_slides/aichetalk/.hg/store/data/tocloft.sty.i': Input/output
error
rm: cannot remove 'amyao/Documents/toshiba_Research2014/AIChE
prep/talks_slides/aichetalk/.hg/store/data/tsweep001.pdf.i': Input/output
error
rm: cannot remove 'amyao/Documents/toshiba_Research2014/AIChE
prep/talks_slides/aichetalk/.hg/store/data/uw.jpg.d': Input/output error
rm: cannot remove 'amyao/Documents/toshiba_Research2014/AIChE
prep/talks_slides/aichetalk/.hg/store/data/uw.jpg.i': Input/output error
***@***.***:/mirror/ARCHIVE$ ls -l
amyao/Documents/toshiba_Research2014/AIChE\
prep/talks_slides/aichetalk/.hg/store/data/
ls: cannot access 'amyao/Documents/toshiba_Research2014/AIChE
prep/talks_slides/aichetalk/.hg/store/data/tocloft.sty.i': Input/output
error
ls: cannot access 'amyao/Documents/toshiba_Research2014/AIChE
prep/talks_slides/aichetalk/.hg/store/data/tsweep001.pdf.i': Input/output
error
ls: cannot access 'amyao/Documents/toshiba_Research2014/AIChE
prep/talks_slides/aichetalk/.hg/store/data/uw.jpg.d': Input/output error
ls: cannot access 'amyao/Documents/toshiba_Research2014/AIChE
prep/talks_slides/aichetalk/.hg/store/data/uw.jpg.i': Input/output error
total 0
-????????? ? ? ? ?            ? tocloft.sty.i
-????????? ? ? ? ?            ? tsweep001.pdf.i
-????????? ? ? ? ?            ? uw.jpg.d
-????????? ? ? ? ?            ? uw.jpg.i
***@***.***:/mirror/ARCHIVE$

**Comment by jbraw** [comment]
Yes, I think it's fairly easy to extend all the pieces (KF, target, etc.)
but why wasn't it  done already in MPCTools?

I was wondering if there was some clever fix for taking a problem with
nonzero D and using what we have already in MPCtools to handle it. So then
you would use that trick and not write a code that explicitly handled a D
matrix entry.

If there's no clever trick, I would expect that we should extend MPCTools
to treat this case. It does show up in applications as Titus just found out.

Please copy the group on this thread.

Thanks.

Jim

**Comment by jbraw** [comment]
Can someone retrieve Matthias's peripherals since today is his last day. He
doesn't need them anymore today.

Thanks.

Jim
